name: Trigger auto deployment for ca-purchase-tickets-worker

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ master ]
    tags:
      - worker-*
    paths:
    - '**'
    - '.github/workflows/ca-purchase-tickets-worker-AutoDeployTrigger-bb21ef47-2bfb-42d8-bb40-b0f45322036d.yml'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
    env:
          ACR_NAME: ${{ secrets.PERSONAL_WEBSITE_ACR_NAME }}
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
          CONTAINER_APP_NAME: ${{ secrets.CONTAINER_APP_NAME }}
          IMAGE_TAG: v1.${{ github.sha }}
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_GITHUB_OIDC }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push image
        run: |
          az acr login --name $ACR_NAME
          IMAGE="$ACR_NAME.azurecr.io/$CONTAINER_APP_NAME:$IMAGE_TAG"
          docker build -t $IMAGE ./aca_scaling_worker
          docker push $IMAGE   

      - name: Deploy to Container App
        run: |
          IMAGE="$ACR_NAME.azurecr.io/$CONTAINER_APP_NAME:$IMAGE_TAG"
          az containerapp update \
            --name $CONTAINER_APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --image $IMAGE          
